import type { Metadata } from "next";
import "./globals.css";
import Header from "./ui/layout/Header";
import { lufga } from "./FontSetting";
import ScrollAnimations from "./ui/component/animate";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lufga.variable}`}>
        <Header />

        <ScrollAnimations />
        
        {children}
      </body>
    </html>
  );
}
